name: Save Posts

on:
    push:
        branches: ['main']

permissions: write-all

jobs:
  fetch_api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install requests

      - name: Save Posts
        run: python posts.py

      - name: Commit and push
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git pull
          git add posts/*
          git commit -m "Update posts"
          git push
